server:
  port: 9100

  #Eureka Configuration
eureka:
  client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
                  defaultZone: http://localhost:9000/eureka
        instance:
                preferIpAddress: true

spring:
  application:
              name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: ROLE-SERVICE
          uri: lb://ROLE-SERVICE
          predicates:
            - Path=/roles/**

